# Target Python version
target-version = "py311"

# Line length and indentation
line-length = 88
indent-width = 4

[lint]
# Enable all rules by default
select = ["ALL"]

# Ignore specific rules
ignore = [
    "E501",  # Line length violations
    "D203",  # Incompatible with D211 (no-blank-line-before-class)
    "D213",  # Incompatible with D212 (multi-line-summary-first-line)
    "COM812",  # Conflicts with formatter
]

# Avoid trying to fix flake8-bugbear (`B`) violations
unfixable = ["B"]

[lint.per-file-ignores]
"__init__.py" = ["E402", "F401"]

[format]
# Use double quotes for strings
quote-style = "double"

# Indent with spaces
indent-style = "space"

# Line endings
line-ending = "lf"
